name: Deploy to University Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server via SSH
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          FOLDER: ${{ secrets.SERVER_FOLDER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST "
            cd $FOLDER &&
            git pull &&
            npm install &&
            npm run build &&
            pm2 restart all || pm2 start npm --name 'next-app' -- run start
          "